### ISSUE TITLE
passwords

### ISSUE THREAD

**Issue by 274188A** [cmertz11/OpenTraumaRegistry#9]
Hi, nice project.  I also setup registries like this in a research context and plan to use similar tech.

_(tip - best to not upload the conn strings with pwds)_

**Comment by cmertz11** [comment]
John, 

Thanks for the tip.  I’m going to need many more.  
We’re you able to build and run by chance?

Thanks,

Chris

**Comment by cmertz11** [comment]
Changed password to {password} and updated documentation.
